services:
  catalog:
    image: postgres:15
    container_name: airbyte-catalog
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - airbyte_internal
volumes:
  pg_data:
networks:
  airbyte_internal:
    name: airbyte_airbyte_internal
    external: true